import React, { useState, useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import CircularProgress from '@mui/material/CircularProgress';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';


import Link from 'next/link'

function weather() {

    const [urlAPI, setUrlAPI] = useState('https://api.openweathermap.org/data/2.5/weather?lat=19.4517&lon=-70.69703&lang=en&units=metric&appid=7231c79e8c90736a60b3fc1e0f9d2f27');
    const [weather, setWeather] = useState(null);
    const [loading, setLoading] = useState(true);

    // OBTENER DATA DE API Y GUARDAR EN UN OBJETO
    useEffect(() => {
        fetch(urlAPI)
            .then(res => res.json())
            .then(data => {
                console.log(data);

                const weatherData = {
                    main: data.weather[0].main,
                    description: data.weather[0].description,
                    temp: data.main.temp,
                    city: data.name,
                };

                setWeather(weatherData);
                setLoading(false);
            });
    }, []);


    return (
        <div >
            <Head>
                <title>WeatherApp</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* NAVBAR */}
            <Box sx={{ flexGrow: 1 }}>
                <AppBar position="static">
                    <Toolbar variant='dense'>
                        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                            WeatherApp
                        </Typography>
                        <Link href="/" passHref>
                            <Button color="inherit">Home</Button>
                        </Link>
                    </Toolbar>
                </AppBar>
            </Box>
            {/* CONTENIDO DE PAGINA */}
            <main className={styles.main}>
                <div className={styles.description}>
                    {/* LOADER */}
                    {loading ?
                        <CircularProgress />
                        : null}
                    {weather ? (
                        // DATOS DE API
                        <div>

                            <Card sx={{ maxWidth: 645 }}>
                                <CardMedia
                                    component="img"
                                    height="300"
                                    image="../26302.jpg"
                                    alt="green iguana"
                                />
                                <CardContent>
                                    <Typography gutterBottom variant="h4" component="h1">
                                       <strong>Your're in {weather.city}</strong>
                                    </Typography>
                                    <Typography variant="body2" color="text.secondary">
                                        Your current location is {weather.city}, its weather is <strong>{weather.main}</strong>, more specifically <strong>{weather.description}</strong>. 
                                        Its temperature is <strong>{weather.temp} °C</strong>
                                    </Typography>
                                </CardContent>
                                <CardActions>
                                    <Button size="small">Go back</Button>
                                </CardActions>
                            </Card>

                        </div>
                    ) : null}
                </div>
            </main>
        </div>
    )
}

export default weather