import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import { useState } from 'react';
import Snackbar from '@mui/material/Snackbar';
import Grid from '@mui/material/Grid';

import Link from 'next/link'

export default function Home() {

  const [latitude, setLatitude] = useState('');
  const [longitude, setLongitude] = useState('');

  const [open, setOpen] = useState(false);

  const handleClick = () => {
    setOpen(true);
  };

  const handleClose = (event, reason) => {
    if (reason === 'clickaway') {
      return;
    }

    setOpen(false);
  };



  return (
    <div className={styles.container}>
      <Head>
        <title>WeatherApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid container>
          <Grid item xs={6}>
            <div className={styles.description}>
              <img src='./weather.png' style={{ backgroundRepeat: 0 }} width="500" height="600"></img>
            </div>
          </Grid>
          <Grid item xs={6}>
            <h1 className={styles.title}>
              Welcome to <a href="">WeatherApp!</a>
            </h1>

            <div className={styles.description}>
              <h4>Enter your coordinates to see your current weather</h4>
              <Box
                component="form"
                sx={{
                  '& .MuiTextField-root': { m: 1, width: '25ch' },
                }}
                noValidate
                autoComplete="off"
              >
                <div>
                  <TextField
                    required
                    id="filled-required"
                    label="Latitude"
                    variant='filled'
                    onChange={(e) => setLatitude(e.target.value)}
                  />
                  <TextField
                    required
                    id="outlined-disabled"
                    label="Longitude"
                    variant='filled'
                    onChange={(e) => setLongitude(e.target.value)}
                  />
                </div>
              </Box>
              <Box sx={{ m: 4 }} />
              <Link href="/weather" passHref>
                <Button
                  size="large"
                  variant="outlined">

                  Go to see my Weather
                </Button>
              </Link>
              <Snackbar
                open={open}
                autoHideDuration={6000}
                onClose={handleClose}
                message={latitude}

              />

            </div>

          </Grid>
        </Grid>


      </main>
    </div>
  )
}
