import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import { useState } from 'react';
import Snackbar from '@mui/material/Snackbar';
import Grid from '@mui/material/Grid';

import Link from 'next/link'

function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>WeatherApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid container>
          <Grid item xs={6}>
            <div className={styles.description}>
              <img src='./weather.png' style={{ backgroundRepeat: 0 }} width="500" height="600"></img>
            </div>
          </Grid>
          <Grid item xs={6} className={styles.main}>
            <h1 className={styles.title}>
              Welcome to <a href="">WeatherApp!</a>
            </h1>

            <div className={styles.description}>
              <h4>To know your current weather you just need to enter your coordinates and that's it!</h4>

              <Link href="/weather" passHref>
                <Button
                  size="large"
                  variant="outlined">

                  Go to see my Weather
                </Button>
              </Link>
            </div>

          </Grid>
        </Grid>


      </main>
    </div>
  )
}

export default Home;


